/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Victor
 */
public class TelaGuiaDeViagem extends javax.swing.JFrame {

    /**
     * Creates new form TelaGuiaDeViagem
     */
    public TelaGuiaDeViagem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonCadastrarRoteiro = new javax.swing.JButton();
        ButtonVisualizarRoteiro = new javax.swing.JButton();
        ButtonRoteiroRequisitado = new javax.swing.JButton();
        ButtonLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Guia de Viagem");

        ButtonCadastrarRoteiro.setText("Cadastrar Roteiro");
        ButtonCadastrarRoteiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCadastrarRoteiroActionPerformed(evt);
            }
        });

        ButtonVisualizarRoteiro.setText("Visualizar Meus Roteiros");
        ButtonVisualizarRoteiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVisualizarRoteiroActionPerformed(evt);
            }
        });

        ButtonRoteiroRequisitado.setText("Roteiros Requisitados");
        ButtonRoteiroRequisitado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRoteiroRequisitadoActionPerformed(evt);
            }
        });

        ButtonLogout.setText("Efetuar Logout");
        ButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonCadastrarRoteiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonVisualizarRoteiro, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                    .addComponent(ButtonRoteiroRequisitado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(ButtonCadastrarRoteiro)
                .addGap(39, 39, 39)
                .addComponent(ButtonVisualizarRoteiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(ButtonRoteiroRequisitado)
                .addGap(37, 37, 37)
                .addComponent(ButtonLogout)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLogoutActionPerformed
         TelaLogoutGuiaDeViagem telaGuia = new TelaLogoutGuiaDeViagem();
         telaGuia.setVisible(true);
         setVisible(false);
    }//GEN-LAST:event_ButtonLogoutActionPerformed

    private void ButtonCadastrarRoteiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCadastrarRoteiroActionPerformed
         TelaCadastroRoteiro telaCadastro = new TelaCadastroRoteiro();
         telaCadastro.setVisible(true);
         setVisible(false);         
    }//GEN-LAST:event_ButtonCadastrarRoteiroActionPerformed

    private void ButtonVisualizarRoteiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVisualizarRoteiroActionPerformed
                TelaMeusRoteiros frame = new TelaMeusRoteiros();
                frame.pack();
                frame.setVisible(true);
    }//GEN-LAST:event_ButtonVisualizarRoteiroActionPerformed

    private void ButtonRoteiroRequisitadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRoteiroRequisitadoActionPerformed
                TelaRoteirosRequisitados frame = new TelaRoteirosRequisitados();
                frame.pack();
                frame.setVisible(true);
    }//GEN-LAST:event_ButtonRoteiroRequisitadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGuiaDeViagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGuiaDeViagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGuiaDeViagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGuiaDeViagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGuiaDeViagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCadastrarRoteiro;
    private javax.swing.JButton ButtonLogout;
    private javax.swing.JButton ButtonRoteiroRequisitado;
    private javax.swing.JButton ButtonVisualizarRoteiro;
    // End of variables declaration//GEN-END:variables
}
